<?php
/*
 * This file is part of EC-CUBE
 *
 * Copyright(c) 2000-2015 LOCKON CO.,LTD. All Rights Reserved.
 *
 * http://www.lockon.co.jp/
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; either version 2
 * of the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
 */


namespace Eccube\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * RouteScheduleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RouteScheduleRepository extends EntityRepository
{
    public function getRoute($data) {
        try {
            $qb = $this->createQueryBuilder('rs')
                ->select('r.id')
                ->leftJoin('rs.Bus', 'b')
                ->leftJoin('b.Route', 'r');

            if (!is_null($data['date'])) {
                $date = $data['date']->format('Y/m/d');
                $qb->where('rs.date = :date')->setParameter('date', $date);
            }

            if (!is_null($data['Bus'])) {
                $qb->andWhere('rs.Bus = :Bus')->setParameter('Bus', $data['Bus']);
            }



            $result = $qb->getQuery()
                ->getResult();

            foreach ($result as $id) {

            }

            return $result;
        } catch (\Exception $e) {
            return null;
        }
    }
}
