<?php
/**
 * Created by PhpStorm.
 * User: lqdung1992@gmail.com
 * Date: 02/08/2018
 * Time: 15:02
 */
namespace Eccube\Repository\Master;

use Doctrine\ORM\EntityRepository;

/**
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ApprovalStatusRepository extends EntityRepository
{
}
