<?php
/**
 * Created by PhpStorm.
 * User: lqdung1992@gmail.com
 * Date: 02/05/2018
 * Time: 11:02 PM
 */
namespace Eccube\Repository\Master;

use Doctrine\ORM\EntityRepository;

/**
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BusStopRepository extends EntityRepository
{
}
